### ISSUE TITLE
VScode Avalonia XAML autocompletion doesn't work

### ISSUE THREAD

**Issue by RegreTTO** [AvaloniaUI/AvaloniaVSCode#110]
## Describe the bug
After triggering autocomplete it doesn't work and throws errors in "Avalonia Client" log section in VScode

## To Reproduce

1. Go to <any>.axaml
2. Click on "<" for example
3. See error 

## Expected behavior
I get autocompletion

## Environment 

- OS: Arch Linux
- Avalonia-Version: 11.0.6

## Additional context
<details>
<summary> Error itself </summary>
<pre><code>2024-02-13 20:07:23.837 [info] [Trace - 20:07:23] Sending notification 'textDocument/didChange'.
2024-02-13 20:07:23.843 [info] [Trace - 20:07:23] Sending request 'textDocument/completion - (2)'.
2024-02-13 20:07:23.853 [info] [Trace - 20:07:23] Received notification 'window/logMessage'.
2024-02-13 20:07:23.853 [info] [Error - 20:07:23] OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker: Failed to handle request textDocument/completion 2 - System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AvaloniaLanguageServer.Services.Buffer.GetTextTillLine(Position position) in /Users/prashantvc/Avalonia/src/AvaloniaLSP/AvaloniaLanguageServer/Services/Buffer.cs:line 8
   at AvaloniaLanguageServer.Services.BufferService.GetTextTillPosition(DocumentUri key, Position position) in /Users/prashantvc/Avalonia/src/AvaloniaLSP/AvaloniaLanguageServer/Services/BufferService.cs:line 22
   at AvaloniaLanguageServer.Handlers.CompletionHandler.Handle(CompletionParams request, CancellationToken cancellationToken) in /Users/prashantvc/Avalonia/src/AvaloniaLSP/AvaloniaLanguageServer/Handlers/CompletionHandler.cs:line 29
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext() | Method='textDocument/completion' RequestId='2'
2024-02-13 20:07:23.854 [info] [Trace - 20:07:23] Received response 'textDocument/completion - (2)' in 11ms. Request failed: Internal Error - System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AvaloniaLanguageServer.Services.Buffer.GetTextTillLine(Position position) in /Users/prashantvc/Avalonia/src/AvaloniaLSP/AvaloniaLanguageServer/Services/Buffer.cs:line 8
   at AvaloniaLanguageServer.Services.BufferService.GetTextTillPosition(DocumentUri key, Position position) in /Users/prashantvc/Avalonia/src/AvaloniaLSP/AvaloniaLanguageServer/Services/BufferService.cs:line 22
   at AvaloniaLanguageServer.Handlers.CompletionHandler.Handle(CompletionParams request, CancellationToken cancellationToken) in /Users/prashantvc/Avalonia/src/AvaloniaLSP/AvaloniaLanguageServer/Handlers/CompletionHandler.cs:line 29
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext() (-32603).
2024-02-13 20:07:23.855 [info] [Error - 20:07:23] Request textDocument/completion failed.
2024-02-13 20:07:23.855 [info]   Message: Internal Error - System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AvaloniaLanguageServer.Services.Buffer.GetTextTillLine(Position position) in /Users/prashantvc/Avalonia/src/AvaloniaLSP/AvaloniaLanguageServer/Services/Buffer.cs:line 8
   at AvaloniaLanguageServer.Services.BufferService.GetTextTillPosition(DocumentUri key, Position position) in /Users/prashantvc/Avalonia/src/AvaloniaLSP/AvaloniaLanguageServer/Services/BufferService.cs:line 22
   at AvaloniaLanguageServer.Handlers.CompletionHandler.Handle(CompletionParams request, CancellationToken cancellationToken) in /Users/prashantvc/Avalonia/src/AvaloniaLSP/AvaloniaLanguageServer/Handlers/CompletionHandler.cs:line 29
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()
  Code: -32603 
2024-02-13 20:07:24.854 [info] [Trace - 20:07:24] Sending notification 'textDocument/didSave'.
2024-02-13 20:07:24.856 [info] [Trace - 20:07:24] Received notification 'window/logMessage'.
2024-02-13 20:07:24.857 [info] [Info  - 20:07:24] AvaloniaLanguageServer.Handlers.TextDocumentSyncHandler: DidSaveTextDocumentParams OmniSharp.Extensions.LanguageServer.Protocol.Models.DidSaveTextDocumentParams | Request='OmniSharp.Extensions.LanguageServer.Protocol.Models.DidSaveTextDocumentParams'
2024-02-13 20:07:25.169 [info] [Trace - 20:07:25] Sending notification 'workspace/didChangeWatchedFiles'.</code></pre>
</details>

**Comment by prashantvc** [comment]
@RegreTTO This is fixed in the version v0.0.30, could you confirm that you have latest version of the extension?

**Comment by RegreTTO** [comment]
@prashantvc Yes. I've checked the version right now and it is exactly v0.0.30

**Comment by RegreTTO** [comment]
@timunie It was the first time I installed all avalonia-related plugins, so they are exactly last version

**Comment by timunie** [comment]
11.0.6 is outdated. 11.0.9 is recent.

**Comment by RegreTTO** [comment]
I installed it as said in the docs witch `dotnet new install Avalonia.Templates`. I took version from my `.csproj` file.

**Comment by timunie** [comment]
The templates were maybe not updated yet. They are not always in sync with latest minor version, so please try to update your nugets 🙏

**Comment by calee88** [comment]
@timunie Hello!
How can I update my nugets? I tried
```zsh
dotnet new install Avalonia.Templates::11.0.9
```
I got

Warning: Avalonia.Templates::11.0.9 is not found in NuGet feeds https://api.nuget.org/v3/index.json.
Avalonia.Templates::11.0.9 could not be installed, the package does not exist.

I also searched for the Avalonia.Templates and found that the latest version is 11.0.6.
https://www.nuget.org/packages?q=Avalonia.Templates

**Comment by calee88** [comment]
I tried to update the package versions by manually changing the versions in .csproj file, and rebuild the project. However, the problem persists.

**Comment by calee88** [comment]
I updated the extension to v0.0.29, and the problem has been resolved.

**Comment by RegreTTO** [comment]
Thanks, I'll try downgrading later

**Comment by RegreTTO** [comment]
@calee88 Indeed, downgrading fixes this problem

**Comment by RegreTTO** [comment]
Or not. After rebooting it started to infinitely ask me to build project, but nothing changes. It asks, I build, it asks again and so on

**Comment by timunie** [comment]
@RegreTTO please upload a minimum sample for us to reproduce.

**Comment by RegreTTO** [comment]
@timunie There is no need me to upload such. It is just `dotnet new avalonia.mvvm`, nothing more

**Comment by microhobby** [comment]
I'm having the same issue 😓

**Comment by microhobby** [comment]
Interesting, if I downgrade the extension to the `v0.0.29` it works 🤔

**Comment by LeadManPL** [comment]
I can confirm. Just follow [Avalonia docs](https://docs.avaloniaui.net/docs/get-started/test-drive/create-a-project) to reproduce this error.  Avalonia.Templates::11.0.6 is the newest version available.

```
2024-03-05 15:52:27.694 [info] [Trace - 15:52:27] Sending request 'textDocument/completion - (1)'.
2024-03-05 15:52:27.729 [info] [Trace - 15:52:27] Received notification 'window/logMessage'.
2024-03-05 15:52:27.729 [info] [Error - 15:52:27] OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker: Failed to handle request textDocument/completion 1 - System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AvaloniaLanguageServer.Services.Buffer.GetTextTillLine(Position position) in /Users/prashantvc/Avalonia/src/AvaloniaLSP/AvaloniaLanguageServer/Services/Buffer.cs:line 8
   at AvaloniaLanguageServer.Services.BufferService.GetTextTillPosition(DocumentUri key, Position position) in /Users/prashantvc/Avalonia/src/AvaloniaLSP/AvaloniaLanguageServer/Services/BufferService.cs:line 22
   at AvaloniaLanguageServer.Handlers.CompletionHandler.Handle(CompletionParams request, CancellationToken cancellationToken) in /Users/prashantvc/Avalonia/src/AvaloniaLSP/AvaloniaLanguageServer/Handlers/CompletionHandler.cs:line 29
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext() | Method='textDocument/completion' RequestId='1'
2024-03-05 15:52:27.736 [info] [Trace - 15:52:27] Received response 'textDocument/completion - (1)' in 41ms. Request failed: Internal Error - System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AvaloniaLanguageServer.Services.Buffer.GetTextTillLine(Position position) in /Users/prashantvc/Avalonia/src/AvaloniaLSP/AvaloniaLanguageServer/Services/Buffer.cs:line 8
   at AvaloniaLanguageServer.Services.BufferService.GetTextTillPosition(DocumentUri key, Position position) in /Users/prashantvc/Avalonia/src/AvaloniaLSP/AvaloniaLanguageServer/Services/BufferService.cs:line 22
   at AvaloniaLanguageServer.Handlers.CompletionHandler.Handle(CompletionParams request, CancellationToken cancellationToken) in /Users/prashantvc/Avalonia/src/AvaloniaLSP/AvaloniaLanguageServer/Handlers/CompletionHandler.cs:line 29
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext() (-32603).
2024-03-05 15:52:27.736 [info] [Error - 15:52:27] Request textDocument/completion failed.
2024-03-05 15:52:27.736 [info]   Message: Internal Error - System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AvaloniaLanguageServer.Services.Buffer.GetTextTillLine(Position position) in /Users/prashantvc/Avalonia/src/AvaloniaLSP/AvaloniaLanguageServer/Services/Buffer.cs:line 8
   at AvaloniaLanguageServer.Services.BufferService.GetTextTillPosition(DocumentUri key, Position position) in /Users/prashantvc/Avalonia/src/AvaloniaLSP/AvaloniaLanguageServer/Services/BufferService.cs:line 22
   at AvaloniaLanguageServer.Handlers.CompletionHandler.Handle(CompletionParams request, CancellationToken cancellationToken) in /Users/prashantvc/Avalonia/src/AvaloniaLSP/AvaloniaLanguageServer/Handlers/CompletionHandler.cs:line 29
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()
  Code: -32603 
```

**Comment by doxxx** [comment]
I have the same problem, even after updating all the Avalonia packages in my project to 11.0.9 and with extension v0.0.31.

**Comment by doxxx** [comment]
However, the same happens for a project opened from the Windows filesystem.

**Comment by prashantvc** [comment]
@doxxx the WSL support is untested. Let me check this one windows

**Comment by aneeskA** [comment]
If this helps anyone, `0.0.31` had issues. Downgrading to `0.0.29` resolved the issue.

<img width="623" alt="image" src="https://github.com/AvaloniaUI/AvaloniaVSCode/assets/514419/8f6175a8-a965-4d4f-9268-32357d768e9b">


<img width="245" alt="image" src="https://github.com/AvaloniaUI/AvaloniaVSCode/assets/514419/f41e1d57-af05-4280-afc7-135b68d2b00d">

**Comment by tmp64** [comment]
Can confirm that the issue is fixed in latest commits. But you have to build the latest AvaloniaLSP manually.

**Comment by marcin-przywoski** [comment]
@tmp64 how do I do that?

**Comment by tmp64** [comment]
> @tmp64 how do I do that?

Clone this repo, build `src/AvaloniaLSP` (in Visual Studio or with `dotnet build`) and replace the original version in C:\Users\user\.vscode\extensions\avaloniateam.vscode-avalonia-0.0.31\

**Comment by MikeCodesDotNET** [comment]
Please try the latest build and let me know if that resolves the issue?

**Comment by doxxx** [comment]
I can confirm that the latest version of the extension works for me. After I opened my demo project and tried to perform auto-completion, it popped up the selection list with just an option "Build the project". Selecting that option seemed to trigger a `dotnet build`, I think, but it wasn't clear exactly what it was doing. My suggestion here would be to execute the command in a terminal window so the user can see what's going on. After the build finished, auto-completion worked as expected.

After performing a `dotnet clean`, auto-completion prompted to build the project again as expected. If I manually performed a build, i.e. `dotnet build` in the terminal, then auto-completion begins working as expected.

**Comment by doxxx** [comment]
There's a few problems with the way this is currently implemented.

1. Selecting the "build the project" option in the completion list inserts a space into the active document. While not the end of the world, it would be nice to avoid this.

2. If there are build errors, the "build the project" option completes without any indication that there was an error. Auto-completions simply don't work after the build supposedly completes. You have to go to the Output window and select Avalonia Client from the dropdown to see that there were errors during the build.

**Comment by tifish** [comment]
The auto-completion does not work if I changed `<OutDir>` in .csproj.

**Comment by codergal6502** [comment]
> > [@tmp64](https://github.com/tmp64) how do I do that?
> 
> Clone this repo, build `src/AvaloniaLSP` (in Visual Studio or with `dotnet build`) and replace the original version in C:\Users\user.vscode\extensions\avaloniateam.vscode-avalonia-0.0.31\

I'm getting errors doing this:

```zsh
% git clone https://github.com/AvaloniaUI/AvaloniaVSCode.git
Cloning into 'AvaloniaVSCode'...
remote: Enumerating objects: 1601, done.
remote: Counting objects: 100% (240/240), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 1601 (delta 195), reused 189 (delta 185), pack-reused 1361 (from 2)
Receiving objects: 100% (1601/1601), 1.82 MiB | 1.68 MiB/s, done.
Resolving deltas: 100% (1005/1005), done.
% cd AvaloniaVSCode/src/AvaloniaLSP 
% dotnet build
    /usr/local/share/dotnet/sdk/9.0.202/NuGet.targets(498,5): error MSB3202: The project file "avalearnia/AvaloniaVSCode/src/AvaloniaVS/CompletionEngine/Avalonia.Ide.CompletionEngine/Avalonia.Ide.CompletionEngine.csproj" was not found.
    /usr/local/share/dotnet/sdk/9.0.202/NuGet.targets(498,5): error MSB3202: The project file "avalearnia/AvaloniaVSCode/src/AvaloniaVS/CompletionEngine/Avalonia.Ide.CompletionEngine.DnlibMetadataProvider/Avalonia.Ide.CompletionEngine.DnlibMetadataProvider.csproj" was not found.

Restore failed with 2 error(s) in 0.2s
```

Is there more that needs to be done? I did try `build.sh` and got something similar:

```zsh
avalearnia/AvaloniaVSCode % ./build.sh 
./build.sh: line 4: yarn: command not found
avalearnia/AvaloniaVSCode/src
Restore complete (4.7s)
  AvaloniaLanguageServer failed with 10 error(s) and 1 warning(s) (0.7s)
    /usr/local/share/dotnet/sdk/9.0.202/Microsoft.Common.CurrentVersion.targets(2189,5): warning MSB9008: The referenced project ../../AvaloniaVS/CompletionEngine/Avalonia.Ide.CompletionEngine.DnlibMetadataProvider/Avalonia.Ide.CompletionEngine.DnlibMetadataProvider.csproj does not exist.
    avalearnia/AvaloniaVSCode/src/AvaloniaLSP/AvaloniaLanguageServer/Handlers/CompletionHandler.cs(1,7): error CS0246: The type or namespace name 'Avalonia' could not be found (are you missing a using directive or an assembly reference?)
    avalearnia/AvaloniaVSCode/src/AvaloniaLSP/AvaloniaLanguageServer/Models/Workspace.cs(3,7): error CS0246: The type or namespace name 'Avalonia' could not be found (are you missing a using directive or an assembly reference?)
    avalearnia/AvaloniaVSCode/src/AvaloniaLSP/AvaloniaLanguageServer/Models/Workspace.cs(4,7): error CS0246: The type or namespace name 'Avalonia' could not be found (are you missing a using directive or an assembly reference?)
    avalearnia/AvaloniaVSCode/src/AvaloniaLSP/AvaloniaLanguageServer/Models/Workspace.cs(5,7): error CS0246: The type or namespace name 'Avalonia' could not be found (are you missing a using directive or an assembly reference?)
    avalearnia/AvaloniaVSCode/src/AvaloniaLSP/AvaloniaLanguageServer/Models/Workspace.cs(30,5): error CS0246: The type or namespace name 'Metadata' could not be found (are you missing a using directive or an assembly reference?)
    avalearnia/AvaloniaVSCode/src/AvaloniaLSP/AvaloniaLanguageServer/Models/Workspace.cs(75,12): error CS0246: The type or namespace name 'Metadata' could not be found (are you missing a using directive or an assembly reference?)
    avalearnia/AvaloniaVSCode/src/AvaloniaLSP/AvaloniaLanguageServer/Models/Workspace.cs(76,14): error CS0246: The type or namespace name 'MetadataReader' could not be found (are you missing a using directive or an assembly reference?)
    avalearnia/AvaloniaVSCode/src/AvaloniaLSP/AvaloniaLanguageServer/Handlers/CompletionHandler.cs(80,16): error CS0246: The type or namespace name 'Metadata' could not be found (are you missing a using directive or an assembly reference?)
    avalearnia/AvaloniaVSCode/src/AvaloniaLSP/AvaloniaLanguageServer/Handlers/CompletionHandler.cs(101,53): error CS0246: The type or namespace name 'CompletionKind' could not be found (are you missing a using directive or an assembly reference?)
    avalearnia/AvaloniaVSCode/src/AvaloniaLSP/AvaloniaLanguageServer/Handlers/CompletionHandler.cs(126,14): error CS0246: The type or namespace name 'CompletionEngine' could not be found (are you missing a using directive or an assembly reference?)

Build failed with 10 error(s) and 1 warning(s) in 5.7s
MSBUILD : error MSB1009: Project file does not exist.
Switch: avalearnia/AvaloniaVSCode/src/SolutionParser/SolutionParser.csproj
🎉 Great success
```

Any advice? Thanks!

**Comment by tmp64** [comment]
@codergal6502 This repo uses Git submodules for subprojects. To clone them, run this:
```bash
git submodule init
git submodule update
```

**Comment by codergal6502** [comment]
> > [@tmp64](https://github.com/tmp64) how do I do that?
> 
> Clone this repo, build `src/AvaloniaLSP` (in Visual Studio or with `dotnet build`) and replace the original version in C:\Users\user.vscode\extensions\avaloniateam.vscode-avalonia-0.0.31\

Do I need to do more than this? macOS 14.1, ARM64, VS Code 1.99.2. I'm still getting _⚡Build the project_.

```
AvaloniaLanguageServer/bin/Debug/net8.0 % rm -r ~/.vscode/extensions/avaloniateam.vscode-avalonia-0.0.31/avaloniaServer/*
AvaloniaLanguageServer/bin/Debug/net8.0 % cp -r * ~/.vscode/extensions/avaloniateam.vscode-avalonia-0.0.31/avaloniaServer
```

I did compare the contents of `bin/Debug/net8.0` to the directory I was copying to and they seem like they contain the same stuff, but the parent directory of the one I'm copying to (`avaloniateam.vscode-avalonia-0.0.31`) also contains a bunch of stuff.

For reference, this is what's in my extensions directory:

```
% ls -lA  ~/.vscode/extensions/ | awk '{print $9}'                               

.DS_Store
avaloniateam.vscode-avalonia-0.0.31
extensions.json
golang.go-0.46.1
ms-dotnettools.csdevkit-1.18.23-darwin-arm64
ms-dotnettools.csharp-2.72.27-darwin-arm64
ms-dotnettools.vscode-dotnet-runtime-2.3.1
ms-vscode.hexeditor-1.11.1
```

Or do I need to do this using version 0.0.32 of the extension?

Thank you for the help!

**Comment by MikeCodesDotNET** [comment]
Closing this issue as the extension has been rebuilt from scratch and is now part of Avalonia Accelerate. You may find that this issue has been resolved in the latest version of the extension.
