### ISSUE TITLE
If, when creating a project, dotnet is not installed on the system, the extension goes into eternal loading.

### ISSUE THREAD

**Issue by SignalMQ** [AvaloniaUI/AvaloniaVSCode#114]
### Describe the bug

**Hello everyone!**
The other day I reinstalled the system and after installing vscode, I simply installed the `vscode-avalonia` extension. I expected that the extension would first install the dotnet I needed through another extension `vscode-dotnet-runtime`, but this did not happen.

### To Reproduce

**Prerequisites:**
1) There are no installed dotnet on system.
2) Fresh installation of vscode without any extensions.
3) Only installed `vscode-avalonia` extension.

**Steps to reproduce:**
1) Open folders
2) Click `Create Avalonia Project`
3) Select `avalonia.mvvm` project
4) Select folder to place project files

### Avalonia for VS Code

(no response)

### Avalonia version

(no response)

### VS Code version

v0.0.31

### Relevant log output

```shell
Extension host:
2024-02-18 17:01:22.195 [info] Extension host with pid 9201 started
2024-02-18 17:01:22.250 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-02-18 17:01:22.263 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-02-18 17:01:22.389 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-02-18 17:01:22.517 [info] Eager extensions activated
2024-02-18 17:01:22.673 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-02-18 17:01:22.678 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-02-18 17:01:29.180 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2024-02-18 17:01:29.258 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2024-02-18 17:01:29.356 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-02-18 17:03:12.082 [info] ExtensionService#_doActivateExtension ms-dotnettools.vscode-dotnet-runtime, startup: false, activationEvent: 'onCommand:avalonia.newProject', root cause: AvaloniaTeam.vscode-avalonia
2024-02-18 17:03:12.231 [info] ExtensionService#_doActivateExtension AvaloniaTeam.vscode-avalonia, startup: false, activationEvent: 'onCommand:avalonia.newProject'
2024-02-18 17:03:23.415 [error] Error: spawn dotnet ENOENT
	at Process.onexit (node:internal/child_process:283:19)
	at onErrorNT (node:internal/child_process:476:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Shared:
2024-02-18 17:01:21.954 [info] Started initializing default profile extensions in extensions installation folder. file:///home/sobirjon/.vscode/extensions
2024-02-18 17:01:22.109 [warning] Failed to create default profile extensions manifest in extensions installation folder. file:///home/sobirjon/.vscode/extensions Unable to create file 'vscode-userdata:/home/sobirjon/.vscode/extensions/extensions.json' that already exists when overwrite flag is not set
2024-02-18 17:01:22.109 [info] Completed initializing default profile extensions in extensions installation folder. file:///home/sobirjon/.vscode/extensions
2024-02-18 17:01:22.422 [error] [uncaught exception in sharedProcess]: Event not found: onDidChange: CodeExpectedError: Event not found: onDidChange
    at Object.listen (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:45:4959)
    at E.t (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:44:251)
    at E.q (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:43:4371)
    at w.value (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:43:3602)
    at d.y (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:38:1902)
    at d.z (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:38:1972)
    at d.fire (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:38:2188)
    at MessagePortMain.de (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:36:30422)
    at MessagePortMain.emit (node:events:514:28)
    at Object.emit (node:electron/js2c/utility_init:2:2285)
2024-02-18 17:01:42.337 [info] Getting Manifest... avaloniateam.vscode-avalonia
2024-02-18 17:01:42.349 [info] Installing extension: avaloniateam.vscode-avalonia
2024-02-18 17:01:43.215 [info] Getting Manifest... ms-dotnettools.vscode-dotnet-runtime
2024-02-18 17:01:43.522 [info] Installing extension: ms-dotnettools.vscode-dotnet-runtime avaloniateam.vscode-avalonia
2024-02-18 17:01:48.027 [info] Extension signature is verified: ms-dotnettools.vscode-dotnet-runtime
2024-02-18 17:01:48.130 [info] Extracted extension to file:///home/sobirjon/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.1: ms-dotnettools.vscode-dotnet-runtime
2024-02-18 17:01:48.135 [info] Renamed to /home/sobirjon/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.1
2024-02-18 17:01:48.138 [info] Extracting extension completed. ms-dotnettools.vscode-dotnet-runtime
2024-02-18 17:01:48.227 [error] [uncaught exception in sharedProcess]: Error: ENOENT: no such file or directory, stat '/home/sobirjon/.vscode/extensions/extensions.json.vsctmp': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/home/sobirjon/.vscode/extensions/extensions.json.vsctmp'
    at r.create (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:51:30119)
    at a (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:51:30234)
    at i.fb (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:36631)
    at i.stat (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:29077)
    at async v.stat (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:16223)
    at async Y.tb (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:102:108626)
2024-02-18 17:01:55.678 [info] Extension signature is verified: avaloniateam.vscode-avalonia
2024-02-18 17:01:58.164 [info] Extracted extension to file:///home/sobirjon/.vscode/extensions/avaloniateam.vscode-avalonia-0.0.31: avaloniateam.vscode-avalonia
2024-02-18 17:01:58.175 [info] Renamed to /home/sobirjon/.vscode/extensions/avaloniateam.vscode-avalonia-0.0.31
2024-02-18 17:01:58.177 [info] Extracting extension completed. avaloniateam.vscode-avalonia
2024-02-18 17:01:58.189 [info] Extension installed successfully: ms-dotnettools.vscode-dotnet-runtime
2024-02-18 17:01:58.190 [info] Extension installed successfully: avaloniateam.vscode-avalonia
2024-02-18 17:01:58.262 [error] [uncaught exception in sharedProcess]: Error: ENOENT: no such file or directory, stat '/home/sobirjon/.vscode/extensions/extensions.json.vsctmp': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/home/sobirjon/.vscode/extensions/extensions.json.vsctmp'
    at r.create (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:51:30119)
    at a (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:51:30234)
    at i.fb (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:36631)
    at i.stat (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:29077)
    at async v.stat (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:16223)
    at async Y.tb (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:102:108626)
```

### Additional context

![image](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/77734001/8a035bef-77de-4851-82e4-c398575f8926)

**Comment by lextm** [comment]
The command to create new Avalonia projects doesn't verify .NET runtime presence, so it fails like you describe if no runtime is available.

We have fixed it in [this fork](https://marketplace.visualstudio.com/items?itemName=lextudio.vscode-axaml) and will ship the patch in the next release.
