### ISSUE TITLE
Doesn't Work on Solutions in Directories with Spaces

### ISSUE THREAD

**Issue by lunarcloud** [AvaloniaUI/AvaloniaVSCode#43]
I saw this in my "Extension Host" log

```powershell
2023-09-08 16:07:50.235 [error] SyntaxError: Unexpected token 'E', "
Error: Unk"... is not valid JSON
	at JSON.parse (<anonymous>)
	at updateSolutionModel (c:\Users\ssarette\.vscode\extensions\avaloniateam.vscode-avalonia-0.0.17\out\services\solutionParser.js:62:23)
	at Socket.<anonymous> (c:\Users\ssarette\.vscode\extensions\avaloniateam.vscode-avalonia-0.0.17\out\services\solutionParser.js:98:13)
	at Socket.emit (node:events:513:28)
	at addChunk (node:internal/streams/readable:324:12)
	at readableAddChunk (node:internal/streams/readable:297:9)
	at Readable.push (node:internal/streams/readable:234:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

Dug into it a bit to find the cause...

```powershell
Error: Unknown command 'Thing'.

       c:\Users\ssarette\work\repos\Example Thing  3\Proj\Example.sln
                                            ^^^ No such command
```

**Comment by prashantvc** [comment]
Could you try using the v0.0.18? 
You can download it from the release here https://github.com/AvaloniaUI/AvaloniaVSCode/releases/tag/v0.0.18

install it manually in the VS Code

**Comment by prashantvc** [comment]
Please reopen if you continue to have an issue
