### ISSUE TITLE
Previews don't work on Windows

### ISSUE THREAD

**Issue by Mrcubix** [AvaloniaUI/AvaloniaVSCode#63]
Previews stopped working on windows 10 22H2 & I'm currently encountering 2 different issues with them :

After clicking on the `Build Project` Button on a known working view, it does not seem to render anything and doesn't send an prompt the user with a notification stating the error.
The following logs could be found in the `Avalonia Client` Output tab : 
```log
[info] Command avalonia.previewProcess, file:///c%3A/Users/tinta/Documents/Repo/C%23/OTD/Plugins/0.5.x/Touch-Gestures/Touch-Gestures.UX/Views/MainView.axaml
[info] PreviewServer.start c:\Users\tinta\Documents\Repo\C#\OTD\Plugins\0.5.x\Touch-Gestures\Touch-Gestures.UX\bin\Debug\net7.0\Touch-Gestures.UX.dll
[info] Previewer process started with args: exec,--runtimeconfig "c:\Users\tinta\Documents\Repo\C#\OTD\Plugins\0.5.x\Touch-Gestures\Touch-Gestures.UX.Desktop\bin\Debug\net7.0\Touch-Gestures.UX.Desktop.runtimeconfig.json",--depsfile "c:\Users\tinta\Documents\Repo\C#\OTD\Plugins\0.5.x\Touch-Gestures\Touch-Gestures.UX.Desktop\bin\Debug\net7.0\Touch-Gestures.UX.Desktop.deps.json" "C:\Users\tinta\.nuget\packages\avalonia\11.0.4\tools\netcoreapp2.0\designer\Avalonia.Designer.HostApp.dll",--method avalonia-remote,--transport tcp-bson://127.0.0.1:8001/,--method html,--html-url http://127.0.0.1:8000,"c:\Users\tinta\Documents\Repo\C#\OTD\Plugins\0.5.x\Touch-Gestures\Touch-Gestures.UX.Desktop\bin\Debug\net7.0\Touch-Gestures.UX.Desktop.dll"
[info] Preview server listening on port 8001
[info] Show Preview to side: file:///c%3A/Users/tinta/Documents/Repo/C%23/OTD/Plugins/0.5.x/Touch-Gestures/Touch-Gestures.UX/Views/MainView.axaml
[info] Preview server connected on port 8001
[info] Obtaining AppBuilder instance from TouchGestures.UX.Desktop.Program

[info] Initializing application in design mode

[info] {"Uri":"http://127.0.0.1:8000/"}
[info] Sending StartDesignerSessionMessage

[info] {"SessionId":"e0b8c3da-caeb-4115-b412-6b5e4593a3a5"}
[info] Start designer session message received.
[info] Unhandled exception. 
[info] System.Exception: Origin doesen't match Url
   at Avalonia.DesignerSupport.Remote.HtmlTransport.HtmlWebSocketTransport.AcceptWorker()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

[info] Preview server error: Error: read ECONNRESET
[info] Preview server closed for c:\Users\tinta\Documents\Repo\C#\OTD\Plugins\0.5.x\Touch-Gestures\Touch-Gestures.UX\bin\Debug\net7.0\Touch-Gestures.UX.dll
[info] Previewer process exited with code 3762504530
```
Here is the content of the DevTools, the following lines get spammed repeatedly :  
```log
[Extension Host] Preview server started on port 8001
{Warning} WebSocket connection to 'ws:<URL>/ws' failed: WebSocket is closed before the connection is established.
onPreviewUrlChanged http://127.0.0.1:8000
WebSocket connection to 'ws://127.0.0.1:8000/ws' failed: 
Connection error: [object Event]
onPreviewUrlChanged http://127.0.0.1:8000
Connection error: [object Event]
onPreviewUrlChanged http://127.0.0.1:8000
WebSocket connection to 'ws://127.0.0.1:8000/ws' failed: Insufficient resources
```

![image](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/39861216/cb45cc08-c83a-4ea2-85d1-d5b9bbe17c5d)

<hr>

Another issue related to the preview function happen when attempting to preview a Templated control, result in absolutely nothing happening, the `Build Project` Button stays greyed out, and no errors are printed in the output : 
```log
[info] Command avalonia.previewProcess, file:///c%3A/Users/tinta/Documents/Repo/C%23/OTD/Plugins/0.5.x/Touch-Gestures/Touch-Gestures.UX/Controls/Containers/NodeCanvas.axaml
[info] Show Preview to side: file:///c%3A/Users/tinta/Documents/Repo/C%23/OTD/Plugins/0.5.x/Touch-Gestures/Touch-Gestures.UX/Controls/Containers/NodeCanvas.axaml
[info] Previewer assets generated at C:\Users\tinta\.nuget\packages\avalonia\11.0.4\tools\netcoreapp2.0\designer\Avalonia.Designer.HostApp.dll
[info] Command avalonia.previewProcess, file:///c%3A/Users/tinta/Documents/Repo/C%23/OTD/Plugins/0.5.x/Touch-Gestures/Touch-Gestures.UX/Controls/Containers/NodeCanvas.axaml
[info] Show Preview to side: file:///c%3A/Users/tinta/Documents/Repo/C%23/OTD/Plugins/0.5.x/Touch-Gestures/Touch-Gestures.UX/Controls/Containers/NodeCanvas.axaml
```
Here is the content of the DevTools, and if anyone ask, yes, that's it, there it nothing else.
```log
executing generateAssetsCommand
```

![image](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/39861216/15911886-672d-41fd-9e7d-6a45d3b130ce)

**Comment by prashantvc** [comment]
I am sorry that you're hitting this issue. And the detailed report will help me get to it quicker :)

**Comment by prashantvc** [comment]
@Mrcubix does this happen with new project? If not is it possible to share the reproducible steps/sample

**Comment by Mrcubix** [comment]
Any.

**Comment by prashantvc** [comment]
for both please, no rush. 
I believe this is an edge I may have missed out

**Comment by Mrcubix** [comment]
Here you go, i've added additional log i have been able to acquire if i try to preview anything after just opening vscode.

https://github.com/Mrcubix/MalfunctionningPreview

**Comment by prashantvc** [comment]
Thanks for the repo, I am able to reproduce it. This looks like an issue in the upstream `Avalonia` project. It may take a while to fix it, I am sorry

**Comment by prashantvc** [comment]
@Mrcubix are you filing this in the main Avalonia repo? if not I will keep this open :)

**Comment by Mrcubix** [comment]
No problem, i ended up loosing more time with IRL an issue i had today than using this extension, and i'm glad i was able to provide some help.

**Comment by Mrcubix** [comment]
Indeed fixed, thanks!
