### ISSUE TITLE
Previewer does not check for presence of bin folder & necessary content

### ISSUE THREAD

**Issue by Mrcubix** [AvaloniaUI/AvaloniaVSCode#71]
If you remove the bin and obj folder after getting a successful preview (e.g using a previous version of the extension as it's currently broken right now), and try to open another preview, then an exception will occur trying to open a specified assembly;

```
2023-11-16 18:01:12.532 [info] {"Error":"System.IO.FileNotFoundException: Could not load file or assembly 
'c:\\Users\\tinta\\Documents\\Repo\\C#\\Avalonia\\Examples\\Issues\\Extension\\MalfunctionningPreview\\Malfunctionning-Preview\\bin\\Debug\\net7.0\\Malfunctionning-Preview.dll'. 
The system cannot find the file specified.
File name: '[...]\\Issues\\Extension\\MalfunctionningPreview\\Malfunctionning-Preview\\bin\\Debug\\net7.0\\Malfunctionning-Preview.dll'
   at System.Reflection.Assembly.LoadFile(String path)
   at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath, String xamlFileProjectPath, Double renderScaling)
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass18_0.<OnTransportMessage>b__0()","Handle":null,"Exception":{"ExceptionType":"FileNotFoundException","Message":"Could not load file or assembly '[...]\\Issues\\Extension\\MalfunctionningPreview\\Malfunctionning-Preview\\bin\\Debug\\net7.0\\Malfunctionning-Preview.dll'. The system cannot find the file specified.","LineNumber":null,"LinePosition":null}}

2023-11-16 18:01:12.532 [info] {"Error":"System.IO.FileNotFoundException: Could not load file or assembly 
'[...]\\Issues\\Extension\\MalfunctionningPreview\\Malfunctionning-Preview\\bin\\Debug\\net7.0\\Malfunctionning-Preview.dll'. 
The system cannot find the file specified.
File name: '[...]\\Issues\\Extension\\MalfunctionningPreview\\Malfunctionning-Preview\\bin\\Debug\\net7.0\\Malfunctionning-Preview.dll'
   at System.Reflection.Assembly.LoadFile(String path)
   at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath, String xamlFileProjectPath, Double renderScaling)
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass18_0.<OnTransportMessage>b__0()","Handle":null,"Exception":{"ExceptionType":"FileNotFoundException","Message":"Could not load file or assembly '[...]\\Issues\\Extension\\MalfunctionningPreview\\Malfunctionning-Preview\\bin\\Debug\\net7.0\\Malfunctionning-Preview.dll'. The system cannot find the file specified.","LineNumber":null,"LinePosition":null}}
```

**Comment by lextm** [comment]
We improved the previewer in [our fork](https://marketplace.visualstudio.com/items?itemName=lextudio.vscode-axaml), but to make your repo work still something else is needed,

1. .NET 7 runtime must present, or upgrade to a newer runtime.
2. Avalonia v11.0.2 doesn't work (should be its bug), but v11.3.3 works fine.
